name: Build - Cap Desktop (Windows x64)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 120

    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PNPM (v10.5.2)
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Rust (x86_64-pc-windows-msvc)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          shared-key: x86_64-pc-windows-msvc

      - name: Prepare env
        shell: pwsh
        run: |
          "VITE_ENVIRONMENT=production" | Out-File -FilePath .env -Encoding utf8 -Append
          "RUST_TARGET_TRIPLE=x86_64-pc-windows-msvc" | Out-File -FilePath .env -Encoding utf8 -Append

      # ===================== FFmpeg (full shared) with robust mirrors =====================
      - name: Download FFmpeg (full shared) with retries
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          $urls = @(
            # BtbN 通用“最新 gpl 共享版”（master）
            "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip",
            # BtbN 指定版本（若存在）
            "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n7.1.1-latest-win64-gpl-shared-7.1.zip",
            # gyan.dev 固定包（zip）
            "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-7.1.1-full_build-shared.zip",
            # gyan.dev 全量 7z（release）
            "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z",
            # gyan.dev 全量 7z（git）
            "https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z"
          )

          function Try-Download([string]$u, [string]$out) {
            for ($i=1; $i -le 3; $i++) {
              try {
                Write-Host "Trying ($i/3): $u"
                Invoke-WebRequest -Uri $u -OutFile $out -UseBasicParsing -TimeoutSec 300
                if ((Test-Path $out) -and ((Get-Item $out).Length -gt 5MB)) { return $true }
              } catch {
                Write-Warning "Invoke-WebRequest failed: $($_.Exception.Message)"
                try {
                  & curl.exe -L --retry 3 --retry-all-errors -o $out $u
                  if ((Test-Path $out) -and ((Get-Item $out).Length -gt 5MB)) { return $true }
                } catch {
                  Write-Warning "curl fallback failed."
                }
              }
              Start-Sleep -Seconds 2
            }
            return $false
          }

          $ok = $false
          foreach ($u in $urls) {
            $out = "ffmpeg.pkg"
            if (Test-Path $out) { Remove-Item $out -Force }
            if (Try-Download $u $out) { $ok = $true; break }
          }
          if (-not $ok) { throw "Failed to download a full shared FFmpeg build from all mirrors." }

          # 解压 zip / 7z
          New-Item -ItemType Directory -Force -Path "_ffmpeg" | Out-Null
          if ($out -like "*.zip") {
            Expand-Archive -Path $out -DestinationPath "_ffmpeg" -Force
          } else {
            $seven = "${env:ProgramFiles}\7-Zip\7z.exe"
            if (-not (Test-Path $seven)) { $seven = "C:\Program Files\7-Zip\7z.exe" }
            if (-not (Test-Path $seven)) { throw "7-Zip not found on runner." }
            & "$seven" x $out "-o_ffmpeg" -y | Out-Null
          }

          $bin = Get-ChildItem -Recurse "_ffmpeg" | Where-Object { $_.PSIsContainer -and ($_.Name -ieq "bin") } | Select-Object -First 1
          if (-not $bin) { throw "FFmpeg bin folder not found in archive." }

          # 复制 DLL：既保留备份目录，也扁平到 src-tauri 根（安装后与 Cap.exe 同级）
          New-Item -ItemType Directory -Force -Path "apps/desktop/src-tauri/ffmpeg-bin" | Out-Null
          Copy-Item "$($bin.FullName)\*.dll" "apps/desktop/src-tauri/ffmpeg-bin\" -Force
          Copy-Item "$($bin.FullName)\*.dll" "apps/desktop/src-tauri\" -Force

          Write-Host "DLLs next to Cap.exe (sizes check):"
          Get-ChildItem "apps/desktop/src-tauri\*.dll" | Sort-Object Length -Descending |
            Select-Object Name,Length | Format-Table -AutoSize

      # ===================== 保留原资源并追加 *.dll 和 assets/** =====================
      - name: Disable Updater and append resources (keep assets)
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          $useProd = Test-Path tauri.prod.conf.json
          $src = if ($useProd) { "tauri.prod.conf.json" } else { "tauri.conf.json" }
          $conf = Get-Content $src -Raw | ConvertFrom-Json

          if ($conf.plugins -and $conf.plugins.updater) {
            $conf.plugins.PSObject.Properties.Remove('updater')
          }
          if (-not $conf.bundle) { $conf | Add-Member -MemberType NoteProperty -Name bundle -Value (@{}) }
          if (-not $conf.bundle.resources) { $conf.bundle | Add-Member -MemberType NoteProperty -Name resources -Value (@()) }

          if (-not ($conf.bundle.resources | Where-Object { $_ -eq "assets/**" })) {
            $conf.bundle.resources += "assets/**"
          }
          if (-not ($conf.bundle.resources | Where-Object { $_ -eq "*.dll" })) {
            $conf.bundle.resources += "*.dll"
          }

          $out = if ($useProd) { "tauri-nosign.prod.conf.json" } else { "tauri-nosign.conf.json" }
          $conf | ConvertTo-Json -Depth 100 | Set-Content $out
          Write-Host "bundle.resources:"
          ($conf.bundle.resources) | % { Write-Host " - $_" }

      - name: Preflight check (DLLs & assets)
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          $dlls = Get-ChildItem ".\*.dll" -ErrorAction SilentlyContinue
          if (-not $dlls -or $dlls.Count -eq 0) { throw "no DLLs in src-tauri root" }
          if (-not (Test-Path ".\assets")) { throw "assets folder missing (apps/desktop/src-tauri/assets)" }
          Write-Host "DLL count: $($dlls.Count)  |  assets: OK"

      - name: Neutralize Tauri signing
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          if (Test-Path ".tauri\key.public") { Remove-Item ".tauri\key.public" -Force }
          if (Test-Path ".tauri\key.enc")    { Remove-Item ".tauri\key.enc" -Force }

      - name: Build desktop (Tauri)
        working-directory: apps/desktop
        shell: pwsh
        env:
          CI: "false"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PUBLIC_KEY: ""
          TAURI_SIGNING_PRIVATE_KEY: ""
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ""
        run: |
          pnpm -w cap-setup
          $cfg = if (Test-Path "src-tauri/tauri-nosign.prod.conf.json") { "src-tauri/tauri-nosign.prod.conf.json" } else { "src-tauri/tauri-nosign.conf.json" }
          pnpm tauri build --target x86_64-pc-windows-msvc --config $cfg

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cap-windows-x64
          path: |
            target/**/bundle/**/*.msi
            target/**/bundle/**/*.exe
            target/**/bundle/**/*.zip
            apps/desktop/src-tauri/target/**/bundle/**/*.msi
            apps/desktop/src-tauri/target/**/bundle/**/*.exe
            apps/desktop/src-tauri/target/**/bundle/**/*.zip
          if-no-files-found: warn
