name: Build • Cap Desktop (Windows x64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 75

    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 先装 pnpm，再装 node（启用 pnpm 缓存）
      - name: Set up PNPM (v10.5.2)
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Rust (x86_64-pc-windows-msvc)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          shared-key: x86_64-pc-windows-msvc

      - name: Prepare env
        shell: pwsh
        run: |
          "VITE_ENVIRONMENT=production" | Out-File -FilePath .env -Encoding utf8 -Append
          "RUST_TARGET_TRIPLE=x86_64-pc-windows-msvc" | Out-File -FilePath .env -Encoding utf8 -Append

      # ① 下载 FFmpeg shared（多源容错：BtbN → Gyan），并把 bin/*.dll 放到 src-tauri/ffmpeg-bin
      - name: Download FFmpeg shared DLLs (with fallbacks)
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          $ProgressPreference = 'SilentlyContinue'
          New-Item -ItemType Directory -Force -Path ".\ffmpeg-bin" | Out-Null

          $candidates = @(
            # BtbN 常见命名（有时存在，有时不存在）
            "https://github.com/BtbN/FFmpeg-Builds/releases/latest/download/ffmpeg-n6.1-latest-win64-lgpl-shared-6.1.zip",
            "https://github.com/BtbN/FFmpeg-Builds/releases/latest/download/ffmpeg-n6.1-latest-win64-gpl-shared-6.1.zip",
            # Gyan.dev 稳定“共享 DLL”包（包含 avcodec-61/avformat-61/avfilter-10/avdevice-61 等）
            "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.1.1-full_build-shared.zip"
          )

          $downloaded = $false
          foreach ($u in $candidates) {
            try {
              Write-Host "Trying FFmpeg URL: $u"
              Invoke-WebRequest -Uri $u -OutFile "ffmpeg.zip" -UseBasicParsing -TimeoutSec 120
              if ((Get-Item "ffmpeg.zip").Length -gt 0) { $downloaded = $true; break }
            } catch {
              Write-Warning "Download failed: $u"
            }
          }

          if (-not $downloaded) {
            throw "Failed to download FFmpeg shared build from all candidates."
          }

          Expand-Archive -Path "ffmpeg.zip" -DestinationPath ".\_ffmpeg" -Force

          # 寻找 bin 目录并复制全部 DLL
          $bin = Get-ChildItem -Recurse ".\_ffmpeg" | Where-Object { $_.PSIsContainer -and ($_.Name -ieq "bin") } | Select-Object -First 1
          if (-not $bin) { throw "FFmpeg bin folder not found in extracted archive." }

          Copy-Item "$($bin.FullName)\*.dll" ".\ffmpeg-bin\" -Force
          Write-Host "Copied FFmpeg DLLs:"
          Get-ChildItem ".\ffmpeg-bin" | % { Write-Host $_.Name }

      # ② 关闭 Updater，并把 ffmpeg-bin/*.dll 注入 bundle.resources
      - name: Disable Updater & inject FFmpeg resources
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          $prod = Test-Path tauri.prod.conf.json
          $src  = if ($prod) { "tauri.prod.conf.json" } else { "tauri.conf.json" }
          Write-Host "Using base config: $src"
          $conf = Get-Content $src -Raw | ConvertFrom-Json

          if ($conf.plugins -and $conf.plugins.updater) {
            $conf.plugins.PSObject.Properties.Remove('updater')
          }

          if (-not $conf.bundle) { $conf | Add-Member -MemberType NoteProperty -Name bundle -Value (@{}) }
          if (-not $conf.bundle.resources) { $conf.bundle | Add-Member -MemberType NoteProperty -Name resources -Value (@()) }
          if (-not ($conf.bundle.resources | Where-Object { $_ -eq "src-tauri/ffmpeg-bin/*.dll" })) {
            $conf.bundle.resources += "src-tauri/ffmpeg-bin/*.dll"
          }

          $out = if ($prod) { "tauri-nosign.prod.conf.json" } else { "tauri-nosign.conf.json" }
          $conf | ConvertTo-Json -Depth 100 | Set-Content $out
          Write-Host "Written config: $out"

      # ③ 构建（使用我们生成的无签名“生产”配置）
      - name: Build desktop (Tauri)
        working-directory: apps/desktop
        shell: pwsh
        run: |
          pnpm -w cap-setup
          $cfg = if (Test-Path "src-tauri/tauri-nosign.prod.conf.json") { "src-tauri/tauri-nosign.prod.conf.json" } else { "src-tauri/tauri-nosign.conf.json" }
          pnpm tauri build --target x86_64-pc-windows-msvc --config $cfg
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ④ 上传产物（同时匹配根 target/** 和 src-tauri/target/** 两种输出位置）
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cap-windows-x64
          path: |
            target/**/bundle/**/*.msi
            target/**/bundle/**/*.exe
            target/**/bundle/**/*.zip
            apps/desktop/src-tauri/target/**/bundle/**/*.msi
            apps/desktop/src-tauri/target/**/bundle/**/*.exe
            apps/desktop/src-tauri/target/**/bundle/**/*.zip
          if-no-files-found: warn
