name: Build • Cap Desktop (Windows x64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 75

    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 先装 pnpm，再装 node（需要这个顺序，setup-node 才能启用 pnpm 缓存）
      - name: Set up PNPM (v10.5.2)
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Rust (x86_64-pc-windows-msvc)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          shared-key: x86_64-pc-windows-msvc

      - name: Prepare env
        shell: pwsh
        run: |
          "VITE_ENVIRONMENT=production" | Out-File -FilePath .env -Encoding utf8 -Append
          "RUST_TARGET_TRIPLE=x86_64-pc-windows-msvc" | Out-File -FilePath .env -Encoding utf8 -Append

      # ① 用 Chocolatey 安装 FFmpeg（共享版），并把 bin/*.dll 全量拷入 src-tauri/ffmpeg-bin
      - name: Install FFmpeg via Chocolatey
        shell: pwsh
        run: |
          choco install -y ffmpeg
          # 常见路径：C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin
          $root = "C:\ProgramData\chocolatey\lib\ffmpeg"
          if (-not (Test-Path $root)) { throw "ffmpeg not found in Chocolatey lib: $root" }
          $bin = Get-ChildItem -Recurse $root | Where-Object { $_.PSIsContainer -and ($_.Name -ieq "bin") } | Select-Object -First 1
          if (-not $bin) { throw "ffmpeg bin folder not found under $root" }
          Write-Host "ffmpeg bin: $($bin.FullName)"

          # 复制全部 DLL 到打包资源目录
          New-Item -ItemType Directory -Force -Path "apps/desktop/src-tauri/ffmpeg-bin" | Out-Null
          Copy-Item "$($bin.FullName)\*.dll" "apps/desktop/src-tauri/ffmpeg-bin\" -Force
          Write-Host "Copied FFmpeg DLLs:"
          Get-ChildItem "apps/desktop/src-tauri/ffmpeg-bin" | % { Write-Host $_.Name }

      # ② 关闭 Updater，并把 ffmpeg-bin/*.dll 注入 bundle.resources（让安装包自带 DLL）
      - name: Disable Updater & inject FFmpeg resources
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          $prod = Test-Path tauri.prod.conf.json
          $src  = if ($prod) { "tauri.prod.conf.json" } else { "tauri.conf.json" }
          Write-Host "Using base config: $src"
          $conf = Get-Content $src -Raw | ConvertFrom-Json

          # 移除 Updater（否则会因缺少签名私钥而失败）
          if ($conf.plugins -and $conf.plugins.updater) {
            $conf.plugins.PSObject.Properties.Remove('updater')
          }

          # 注入 FFmpeg 资源
          if (-not $conf.bundle) { $conf | Add-Member -MemberType NoteProperty -Name bundle -Value (@{}) }
          if (-not $conf.bundle.resources) { $conf.bundle | Add-Member -MemberType NoteProperty -Name resources -Value (@()) }
          if (-not ($conf.bundle.resources | Where-Object { $_ -eq "src-tauri/ffmpeg-bin/*.dll" })) {
            $conf.bundle.resources += "src-tauri/ffmpeg-bin/*.dll"
          }

          $out = if ($prod) { "tauri-nosign.prod.conf.json" } else { "tauri-nosign.conf.json" }
          $conf | ConvertTo-Json -Depth 100 | Set-Content $out
          Write-Host "Written config: $out"

      # ③ 构建（使用我们生成的无签名“生产”配置）
      - name: Build desktop (Tauri)
        working-directory: apps/desktop
        shell: pwsh
        run: |
          pnpm -w cap-setup
          $cfg = if (Test-Path "src-tauri/tauri-nosign.prod.conf.json") { "src-tauri/tauri-nosign.prod.conf.json" } else { "src-tauri/tauri-nosign.conf.json" }
          pnpm tauri build --target x86_64-pc-windows-msvc --config $cfg
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ④ 上传产物（同时匹配根 target/** 和 src-tauri/target/** 两种输出位置）
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cap-windows-x64
          path: |
            target/**/bundle/**/*.msi
            target/**/bundle/**/*.exe
            target/**/bundle/**/*.zip
            apps/desktop/src-tauri/target/**/bundle/**/*.msi
            apps/desktop/src-tauri/target/**/bundle/**/*.exe
            apps/desktop/src-tauri/target/**/bundle/**/*.zip
          if-no-files-found: warn
