name: Build • Cap Desktop (Windows x64)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 75

    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 先用 action 安装声明版本（按 package.json 的 packageManager：pnpm@10.5.2）
      - name: Set up PNPM (action)
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      # Windows 下再用 npm 强制全局装一遍，确保 PATH 可用（兜底）
      - name: Force install pnpm globally (fallback)
        shell: pwsh
        run: |
          npm i -g pnpm@10.5.2
          pnpm -v
          where pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set up Rust (x86_64-pc-windows-msvc)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Cache Rust
        uses: swatinem/rust-cache@v2
        with:
          shared-key: x86_64-pc-windows-msvc

      - name: Prepare env
        shell: pwsh
        run: |
          "VITE_ENVIRONMENT=production" | Out-File -FilePath .env -Encoding utf8 -Append
          "RUST_TARGET_TRIPLE=x86_64-pc-windows-msvc" | Out-File -FilePath .env -Encoding utf8 -Append

      # 关键：禁用 Updater，避免因无签名私钥而失败
      - name: Disable Updater (skip signing)
        shell: pwsh
        working-directory: apps/desktop/src-tauri
        run: |
          $conf = Get-Content tauri.conf.json -Raw | ConvertFrom-Json
          if ($conf.plugins -and $conf.plugins.updater) {
            $conf.plugins.PSObject.Properties.Remove('updater')
          }
          $conf | ConvertTo-Json -Depth 100 | Set-Content tauri-nosign.conf.json

      - name: Build desktop (Tauri)
        working-directory: apps/desktop
        run: |
          pnpm -w cap-setup
          pnpm build:tauri --target x86_64-pc-windows-msvc --config src-tauri/tauri-nosign.conf.json
        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cap-windows-x64
          path: |
            apps/desktop/src-tauri/target/**/bundle/**/*.msi
            apps/desktop/src-tauri/target/**/bundle/**/*.exe
            apps/desktop/src-tauri/target/**/bundle/**/*.zip
          if-no-files-found: warn
